// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CalcTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CalculationsFeature : Xunit.IClassFixture<CalculationsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Calculations.feature"
#line hidden
        
        public CalculationsFeature(CalculationsFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Calculations", "\tIn order to perform basic calculations\r\n    As a user of this program\r\n    I wan" +
                    "t to be told results of calculations", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.TheoryAttribute(DisplayName="Perform basic operations")]
        [Xunit.TraitAttribute("FeatureTitle", "Calculations")]
        [Xunit.TraitAttribute("Description", "Perform basic operations")]
        [Xunit.InlineDataAttribute("Add", "5", "7", "12", new string[0])]
        [Xunit.InlineDataAttribute("Add", "3", "4", "7", new string[0])]
        [Xunit.InlineDataAttribute("Sub", "4", "1", "3", new string[0])]
        [Xunit.InlineDataAttribute("Sub", "987", "342", "645", new string[0])]
        [Xunit.InlineDataAttribute("Multiply", "7", "3", "21", new string[0])]
        [Xunit.InlineDataAttribute("Multiply", "14", "12", "168", new string[0])]
        [Xunit.InlineDataAttribute("Divide", "121", "11", "11", new string[0])]
        [Xunit.InlineDataAttribute("Divide", "63", "7", "9", new string[0])]
        public virtual void PerformBasicOperations(string operation, string firstNumber, string secondNumber, string resultNumber, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Perform basic operations", exampleTags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given(string.Format("I have provided {0} and a {1}", firstNumber, secondNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When(string.Format("I perform operation \'{0}\'", operation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.Then(string.Format("the result should be {0}", resultNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Perform calculations")]
        [Xunit.TraitAttribute("FeatureTitle", "Calculations")]
        [Xunit.TraitAttribute("Description", "Perform calculations")]
        [Xunit.TraitAttribute("Category", "Superseded")]
        public virtual void PerformCalculations()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Perform calculations", new string[] {
                        "Superseded"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
    testRunner.Given("An outdated test", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 26
    testRunner.When("I perform outdated operation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
    testRunner.Then("Some Result will be produced", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CalculationsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CalculationsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
